name: ctiapp-authproxy
ingress:
  rules:
  - component:
      name: ctiapp-authproxy
      rewrite: /index.php/healthcheck
    match:
      path:
        prefix: /healthcheck
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: nethesis/ctiapp-authproxy
  name: ctiapp-authproxy
