http:
  routers:
    # HTTPS router
    ctiapp-secure:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - websecure
      service: ctiapp
      tls: {}

    # HTTP router (no redirection to HTTPS)
    ctiapp:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - web
      service: ctiapp

  services:
    ctiapp:
      loadBalancer:
        servers:
          - url: "http://app:80"
        healthCheck:
          path: "/index.php/healthcheck"
          interval: "30s"
          timeout: "5s"

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: myresolver
        domain:
          main: ctiapp.local
